# main compiler
#CC := g++

TARGET1 := Synergy

all: $(TARGET1)

$(TARGET1): 
	@echo "Compiling C++ program"
	$(CXX) $(CFLAGS) $(TARGET1).cpp -o $(TARGET1) $(LDFLAGS) $(LIB)

clean:
	@rm -rf $(TARGET1) $(TARGET2)
